#
# Insert ORDERS_TBL (Set-1)
#

INSERT INTO ORDERS_TBL (ORDER_NO, ITEM, SHIPPED) VALUES('1', 'iPad Air 128G WiFi', 'N');
INSERT INTO ORDERS_TBL (ORDER_NO, ITEM, SHIPPED) VALUES('2', 'Roku Express 4K+', 'N');
INSERT INTO ORDERS_TBL (ORDER_NO, ITEM, SHIPPED) VALUES('3', '128GB MicroSD Card', 'N');

#
# Insert ORDERS_TBL (Set-2)
#

INSERT INTO ORDERS_TBL (ORDER_NO, ITEM, SHIPPED) VALUES('4', 'Raspberry Pi 4 Model B 8GB', 'N');
INSERT INTO ORDERS_TBL (ORDER_NO, ITEM, SHIPPED) VALUES('5', 'SanDisk 128GB USB3', 'N');

#
# Delete ORDERS_TBL
#

DELETE FROM ORDERS_TBL;
